"""Generate a btop theme from the active palette.

btop has no include mechanism, so this adapter owns two artifacts: the theme
file itself, and the keys in ``btop.conf`` that select it and turn off its own
background so kitty's opacity and blur show through.

Unlike the niri and kitty adapters there is no activation step: btop exposes no
IPC and reads its config once at startup, so ``activated`` is always False and
a wallpaper change takes effect the next time the task manager is opened.
"""

import re

from core.palette import ThemePalette
from .common import atomic_write, config_home, run_if_available

THEME_NAME = "muzwall"
THEME_FILE = f"{THEME_NAME}.theme"


class BtopAdapter:
    @staticmethod
    def render(palette: ThemePalette) -> str:
        a = palette.ansi
        p = palette

        def grad(start, mid, end) -> dict[str, str]:
            return {
                "start": start.to_hex(),
                "mid": mid.to_hex(),
                "end": end.to_hex(),
            }

        # Flat surfaces first.
        keys: dict[str, str] = {
            # Empty main_bg hands the background back to the terminal, which is
            # what lets kitty's opacity and blur show through instead of btop
            # painting an opaque slab over the rounded window. The renderer
            # adds the surrounding quotes, so the value itself is empty.
            "main_bg": "",
            "main_fg": p.fg_primary.to_hex(),
            "title": p.accent.to_hex(),
            "hi_fg": p.accent_hover.to_hex(),
            "div_line": p.border_subtle.to_hex(),
            "inactive_fg": p.fg_muted.to_hex(),
            "meter_bg": p.bg_elevated.to_hex(),
            "selected_bg": p.selection_bg.to_hex(),
            "selected_fg": p.selection_fg.to_hex(),
            "followed_bg": p.selection_hover.to_hex(),
            "proc_follow_bg": p.selection_hover.to_hex(),
            "proc_pause_bg": p.bg_highlight.to_hex(),
            "proc_misc": p.fg_muted.to_hex(),
            "proc_banner_bg": p.bg_surface.to_hex(),
            "proc_banner_fg": p.accent.to_hex(),
            "graph_text": p.fg_primary.to_hex(),
            "cpu_box": p.bg_surface.to_hex(),
            "mem_box": p.bg_surface.to_hex(),
            "net_box": p.bg_surface.to_hex(),
            "proc_box": p.bg_surface.to_hex(),
        }

        # Gradients. CPU and the process list ride the wallpaper accent so the
        # "busy" signal reads as the same colour as the rest of the desktop;
        # memory, network and temperature keep semantic hues so an actual
        # problem is still distinguishable at a glance.
        for name, colours in (
            ("cpu", grad(p.accent_active, p.accent, p.accent_hover)),
            ("process", grad(p.accent_active, p.accent, p.accent_hover)),
            ("used", grad(p.accent_active, p.accent, p.accent_hover)),
            ("available", grad(a["green"], a["green"], a["bright_green"])),
            ("cached", grad(a["blue"], a["blue"], a["bright_blue"])),
            ("free", grad(a["blue"], a["blue"], a["bright_blue"])),
            ("download", grad(a["cyan"], a["cyan"], a["bright_cyan"])),
            ("upload", grad(a["magenta"], a["magenta"], a["bright_magenta"])),
            ("temp", grad(a["green"], a["yellow"], a["red"])),
        ):
            for slot, value in colours.items():
                keys[f"{name}_{slot}"] = value

        width = max(len(k) for k in keys)
        body = [
            "# Generated by Muzwall from the current wallpaper accent.",
            "# Edits are overwritten on the next wallpaper change.",
            "#",
            '# btop docs: colors are "#RRGGBB", "#BB" (grayscale) or "r g b".',
            "# An empty main_bg defers to the terminal background.",
            "",
        ]
        body += [f'theme[{k.ljust(width)}]="{v}"' for k, v in keys.items()]
        return "\n".join(body) + "\n"

    @classmethod
    def apply(cls, palette: ThemePalette, activate: bool = True) -> dict[str, str | bool]:
        config_dir = config_home() / "btop"
        themes_dir = config_dir / "themes"
        theme_path = themes_dir / THEME_FILE
        conf_path = config_dir / "btop.conf"
        result: dict[str, str | bool] = {
            "artifact": str(theme_path),
            "activated": False,
        }

        themes_dir.mkdir(parents=True, exist_ok=True)
        rendered = cls.render(palette)
        unchanged = False
        try:
            unchanged = theme_path.read_text(encoding="utf-8") == rendered
        except OSError:
            pass
        if not unchanged:
            atomic_write(theme_path, rendered)
        result["changed"] = not unchanged
        result["theme"] = THEME_NAME

        # btop.conf cannot include anything, so the selector keys have to be
        # edited in place. Seed the file from btop's own defaults on first run
        # rather than shipping a partial config, then patch just those keys.
        if not conf_path.exists():
            ok, stdout = run_if_available(["btop", "--default-config"], timeout=10.0)
            if ok and stdout.strip():
                atomic_write(conf_path, stdout if stdout.endswith("\n") else stdout + "\n")
            else:
                # btop is missing or refused; write a minimal usable config so
                # the next manual run still lands on the generated theme.
                atomic_write(
                    conf_path,
                    f'color_theme = "{THEME_NAME}"\ntheme_background = false\ntruecolor = true\n',
                )

        try:
            existing = conf_path.read_text(encoding="utf-8")
        except OSError:
            existing = ""

        patched = existing
        for key, value in (
            ("color_theme", f'"{THEME_NAME}"'),
            # False hands the background to kitty so the window's opacity and
            # blur apply to btop instead of being covered by an opaque fill.
            ("theme_background", "false"),
            ("truecolor", "true"),
        ):
            pattern = re.compile(rf"^\s*{key}\s*=.*$", re.MULTILINE)
            line = f"{key} = {value}"
            if pattern.search(patched):
                patched = pattern.sub(line, patched, count=1)
            else:
                patched = patched.rstrip() + f"\n{line}\n"
        if patched != existing:
            atomic_write(conf_path, patched)

        result["config"] = str(conf_path)
        return result
