"""Best-effort GTK theme tokens.

GTK 4/libadwaita does not promise that arbitrary user CSS can replace every
component token. We generate conservative tokens and report the artifact; this
is intentionally not described as a universal libadwaita override.
"""

from core.palette import ThemePalette
from .common import atomic_write, config_home


class GTKAdapter:
    @classmethod
    def render(cls, palette: ThemePalette) -> str:
        fg = palette.fg_primary.to_hex()
        bg = palette.bg_deep.to_hex()
        base = palette.bg_surface.to_hex()
        elev = palette.bg_elevated.to_hex()
        muted = palette.fg_muted.to_hex()
        accent = palette.accent.to_hex()
        sel = palette.selection_bg.to_hex()
        return f"""/* Generated by Muzwall. Tokens only -- the active GTK theme owns
   widget states (hover/selected/active), so its behaviour is never broken. */
@define-color accent_color {accent};
@define-color accent_bg_color {accent};
@define-color accent_fg_color {fg};
@define-color window_bg_color {bg};
@define-color window_fg_color {fg};
@define-color view_bg_color {base};
@define-color view_fg_color {fg};
@define-color headerbar_bg_color {bg};
@define-color headerbar_fg_color {fg};
@define-color headerbar_backdrop_color {bg};
@define-color card_bg_color {elev};
@define-color dialog_bg_color {base};
@define-color popover_bg_color {base};

/* Classic GTK named colours so GTK3 apps pick up the palette for their
   native hover/selection states instead of falling back to defaults. */
@define-color theme_bg_color {bg};
@define-color theme_fg_color {fg};
@define-color theme_base_color {base};
@define-color theme_text_color {fg};
@define-color theme_selected_bg_color {sel};
@define-color theme_selected_fg_color {fg};
@define-color theme_unfocused_bg_color {bg};
@define-color theme_unfocused_fg_color {muted};
@define-color theme_unfocused_base_color {base};
@define-color theme_unfocused_text_color {fg};
@define-color theme_unfocused_selected_bg_color {sel};
@define-color theme_unfocused_selected_fg_color {fg};
@define-color theme_borders_color {palette.border_subtle.to_hex()};
@define-color theme_unfocused_borders_color {palette.border_subtle.to_hex()};
@define-color theme_dark_color {bg};
@define-color theme_light_color {elev};
"""

    @classmethod
    def apply(cls, palette: ThemePalette, activate: bool = True) -> dict[str, list[str]]:
        paths = []
        for version in ("gtk-3.0", "gtk-4.0"):
            # Keep the user's gtk.css intact. The user can add one include line
            # to opt into the generated layer.
            path = config_home() / version / "muzwall.css"
            atomic_write(path, cls.render(palette))
            paths.append(str(path))
            if activate:
                cls._ensure_import(config_home() / version / "gtk.css")
        return {"artifacts": paths}

    @staticmethod
    def _ensure_import(path) -> None:
        marker = "/* muzwall:begin */"
        end_marker = "/* muzwall:end */"
        existing = path.read_text(encoding="utf-8") if path.exists() else ""
        start = existing.find(marker)
        if start >= 0:
            end = existing.find(end_marker, start)
            existing = existing[:start] + (existing[end + len(end_marker):] if end >= 0 else "")
        content = existing.rstrip() + f'\n\n{marker}\n@import url("muzwall.css");\n{end_marker}\n'
        atomic_write(path, content)
