"""Generate a Kitty palette without rewriting the user's main kitty.conf."""

from core.palette import ThemePalette
from .common import atomic_write, config_home, run_if_available


class KittyAdapter:
    @staticmethod
    def render(palette: ThemePalette) -> str:
        colours = palette.ansi
        lines = [
            "# Generated by Muzwall. Include this file from kitty.conf.",
            f"background {palette.bg_deep.to_hex()}",
            f"foreground {palette.fg_primary.to_hex()}",
            f"selection_background {palette.accent.to_hex()}",
            f"selection_foreground {palette.fg_primary.to_hex()}",
            f"cursor {palette.accent.to_hex()}",
            f"cursor_text_color {palette.bg_deep.to_hex()}",
        ]
        for index, name in enumerate(("black", "red", "green", "yellow", "blue", "magenta", "cyan", "white")):
            lines.append(f"color{index} {colours[name].to_hex()}")
        for index, name in enumerate(("bright_black", "bright_red", "bright_green", "bright_yellow", "bright_blue", "bright_magenta", "bright_cyan", "bright_white"), start=8):
            lines.append(f"color{index} {colours[name].to_hex()}")
        return "\n".join(lines) + "\n"

    @classmethod
    def apply(cls, palette: ThemePalette, activate: bool = True) -> dict[str, str | bool]:
        path = config_home() / "kitty" / "muzwall-theme.conf"
        result: dict[str, str | bool] = {"artifact": str(path), "activated": False}
        rendered = cls.render(palette)
        try:
            if path.read_text(encoding="utf-8") == rendered:
                result["include"] = f"include {path}"
                return result
        except OSError:
            pass
        atomic_write(path, rendered)
        if activate:
            kitty_conf = path.parent / "kitty.conf"
            marker = "# muzwall:theme"
            existing = kitty_conf.read_text(encoding="utf-8") if kitty_conf.exists() else ""
            if marker not in existing:
                existing = existing.rstrip() + f'\n\n{marker}\ninclude {path.name}\n'
                atomic_write(kitty_conf, existing)
            ok, message = run_if_available(["pkill", "-USR1", "kitty"])
            result["activated"] = ok
            if message:
                result["message"] = message
        result["include"] = f"include {path}"
        return result
