"""Drive Niri's own chrome from the wallpaper palette.

Niri has no D-Bus/colour-scheme interface, so the only way to recolour the
compositor is to render a KDL fragment and hot-reload the config. We keep the
generated file separate from the hand-written ``config.kdl``: the user's config
``include``s this file, and because included nodes merge with the parent's own
``layout``/``recent-windows`` blocks we only ever emit the colour-bearing
sub-blocks here.

The accent that muzwall already derives from the wallpaper therefore ends up on
the focus ring, tab indicator, insert hint and switcher highlight, and it
re-applies live through ``niri msg action load-config-file``.
"""

from core.palette import ThemePalette
from .common import atomic_write, config_home, run_if_available


class NiriAdapter:
    """Render ``~/.config/niri/muzwall-theme.kdl`` and hot-reload niri."""

    FILENAME = "muzwall-theme.kdl"
    # KDL comments start with "//", not "#" -- a '#' would be parsed as an
    # identifier and make the whole config fail to load.
    INCLUDE_MARKER = "// muzwall:theme"

    @staticmethod
    def render(palette: ThemePalette) -> str:
        accent = palette.accent.to_hex()
        accent_hover = palette.accent_hover.to_hex()
        accent_active = palette.accent_active.to_hex()
        inactive = palette.border_subtle.to_hex()
        # The insert hint sits over arbitrary wallpaper pixels, so it needs to
        # stay translucent to remain readable.
        hint = _alpha(palette.border_active, 0.55)

        lines = [
            "// Generated by Muzwall. Do not edit; edit the muzwall adapter instead.",
            "// Included from config.kdl -- colours follow the wallpaper hue.",
            "",
            "layout {",
            "    focus-ring {",
            "        width 2",
            f'        active-gradient from="{accent}" to="{accent_hover}" angle=45',
            f'        inactive-gradient from="{inactive}" to="{accent_active}" angle=225',
            f'        urgent-gradient from="{accent_active}" to="{accent}" angle=45',
            "    }",
            "",
            "    tab-indicator {",
            f'        active-color "{accent}"',
            f'        inactive-color "{inactive}"',
            f'        urgent-color "{accent_hover}"',
            "    }",
            "",
            "    insert-hint {",
            f'        color "{hint}"',
            "    }",
            "}",
            "",
            "recent-windows {",
            "    highlight {",
            f'        active-color "{accent}"',
            f'        urgent-color "{accent_hover}"',
            "        corner-radius 14",
            "        padding 6",
            "    }",
            "}",
        ]
        return "\n".join(lines) + "\n"

    @classmethod
    def apply(cls, palette: ThemePalette, activate: bool = True) -> dict[str, str | bool]:
        config_dir = config_home() / "niri"
        path = config_dir / cls.FILENAME
        result: dict[str, str | bool] = {"artifact": str(path), "activated": False}

        rendered = cls.render(palette)
        unchanged = False
        try:
            unchanged = path.read_text(encoding="utf-8") == rendered
        except OSError:
            pass
        if not unchanged:
            atomic_write(path, rendered)

        if activate:
            config_path = config_dir / "config.kdl"
            existing = config_path.read_text(encoding="utf-8") if config_path.exists() else ""
            if cls.INCLUDE_MARKER not in existing:
                # Repair an earlier bad marker rather than appending a second
                # include, which would trip niri's duplicate-node checks.
                lines = [
                    line for line in existing.splitlines()
                    if line.strip() not in ('# muzwall:theme', '// muzwall:theme')
                ]
                existing = "\n".join(lines).rstrip()
                existing = (
                    existing
                    + f'\n\n{cls.INCLUDE_MARKER}\ninclude "{cls.FILENAME}"\n'
                )
                atomic_write(config_path, existing)

            # `niri msg action load-config-file` exits 0 even when the config
            # fails to parse, so calling it blind reports success while niri
            # keeps running the previous config. Validate first and refuse to
            # reload on a bad file, otherwise a malformed fragment would look
            # applied and the accent would silently stop tracking.
            if not config_path.exists():
                result["message"] = "config.kdl not found; skipped reload"
            else:
                valid, detail = run_if_available(
                    ["niri", "validate", "--config", str(config_path)], timeout=20.0
                )
                if not valid:
                    result["message"] = (
                        "config failed validation; not reloading. "
                        "Fix ~/.config/niri/config.kdl. " + (detail or "")
                    ).strip()
                else:
                    ok, message = run_if_available(
                        ["niri", "msg", "action", "load-config-file"]
                    )
                    result["activated"] = ok
                    if message:
                        result["message"] = message
        result["include"] = f'include "{path}"'
        result["changed"] = not unchanged
        return result


def _alpha(colour, alpha: float) -> str:
    """Return ``colour`` as ``#rrggbbaa`` with the given alpha."""
    hex_value = colour.to_hex().lstrip("#")
    return f"#{hex_value}{round(max(0.0, min(1.0, alpha)) * 255):02x}"